### ISSUE TITLE
Add another option as meta name 

### ISSUE THREAD

**Issue by trim21** [Zod-/grunt-userscript-meta#2]
There are some meaningless limit in `name` field, but name of a userScript has no such limit.

**Comment by Trim21** [comment]
Or maybe  `userscript.name`  will overwrite `name`.

**Comment by Zod-** [comment]
Uhh it's been a while. Sure, I'll give it a try.
Maybe leave the localization string empty? Not sure if that's possible.

**Comment by Trim21** [comment]
In fact I have write a userscript and publish it on website before I'm using grunt, and its name is not a valid npm package name. If I use it as my npm package name, some npm command will not work until I "correct" it. And `name` matadata is the key of userscript file in `tampermonkey` on Chrome. So I must keep if unchanged. Therefore localization can't help with this case...

I read the code and found that `pkg.userscript.name` has been used for localization, Seems that my suggestion is not suitable... 


Sorry for my poor English.
